"""Conservative corrections to the original DSSD lecture sequence."""
from lecture_editor import Page, ROOT, PAGES, pre
import re

def calibration():
    p=Page(PAGES[9])
    p.replace('Pie 0-48','Pie 0-47'); p.replace('Ring 0-48','Ring 0-47')
    for a in p.container(5).find_all('a'):
        if a.get_text()=='zhihuanli.github.io': a.decompose()
    p.replace('创建对象时需要先给出允许搜索的最大峰数，例如：\n创建对象时需要先给出允许搜索的最大峰数，例如：','创建对象时需要先给出允许搜索的最大峰数，例如：')
    p.replace('其中 niter 控制本底的平滑程度。一般来说，niter 越大，本底越平滑，也越容易压低；但本底减除不能过度，否则会侵入真实峰区，甚至在峰区附近产生不合理的负值。这里的原则是让本底足够平滑，同时尽量不破坏真实峰形。','niter 是迭代次数，决定 clipping 窗口覆盖的尺度；它不是简单的平滑强度。窗口应能跨过待分离的峰。将估计本底叠加在原谱上检查；本底扣除后的谱只用于寻找候选峰，峰位拟合仍使用原始计数谱。')
    p.replace('其中 sigma 反映待寻找峰的大致宽度','其中 sigma 以 bin 为单位，反映待寻找峰的大致宽度')
    p.append(5,'<p>接口与参数说明：<a href="https://root.cern.ch/doc/master/classTSpectrum.html">ROOT TSpectrum reference</a>。</p>')
    p.paragraph(5,'其中 niter','<p>niter 是迭代次数，控制 clipping 窗口覆盖的尺度，不是简单的平滑强度。窗口需要跨过待分离的峰。将估计本底叠加在原谱上检查；本底扣除后的谱用于寻找候选峰，峰位拟合仍使用原始计数谱。</p>')
    p.paragraph(7,'其中 sigma','<p>sigma 以 bin 为单位描述预期峰宽；threshold 是相对于搜索结果中最高峰的阈值。它们控制候选峰集，不能独立判断某个结构是否为真实谱线。</p>')
    for i in [2,4]:
        p.code(i,p.code(i).replace('TH1I','TH1').replace('pe[0-48]','pe[0-47]'))
    p.code(3,p.code(3).replace('pe[0-48]','pe[0-47]'))
    p.code(6,p.code(6).replace('TFile *f =','TFile *fgamma =').replace('f->Get','fgamma->Get').replace('hpeak->Add(hpeak, hbg, 1, -1);','hpeak->Add(hbg, -1);').replace('hpeak->Draw();','h0->Draw();').replace('h0->Draw("same");','hpeak->Draw("same");'))
    p.replace('auto im1 = m1.find(762);','auto im1 = m1.find(762);')
    # Keep the original function-based search example, without modifying its input.
    old=p.container(10).find('pre').get_text()
    code=old.replace('TH1F *h = NULL, *hb = NULL;','TH1 *h = nullptr, *hb = nullptr;')
    code=code.replace('h = (TH1F*)gROOT->FindObject(hname);','TH1 *source = dynamic_cast<TH1*>(gROOT->FindObject(hname));\n  h = source ? static_cast<TH1*>(source->Clone(hname+"_search")) : nullptr;')
    code=code.replace('h->Add(h, hb, 1, -1);','h->Add(hb, -1);')
    p.container(10).find('pre').replace_with(__import__('bs4').BeautifulSoup(pre(code),'html.parser'))
    (ROOT/'chapt3/peaks.C').write_text('#include <TSpectrum.h>\n#include <TH1.h>\n#include <TROOT.h>\n#include <TPolyMarker.h>\n#include <TLatex.h>\n#include <TString.h>\n#include <map>\n#include <vector>\n#include <iostream>\nusing namespace std;\n'+code+'\n')
    p.patch_code(12,'peaks("hpeak",ge);','peaks("hpeak", ge, 0.05, 0); // 已扣除本底，不重复扣除')
    p.patch_code(14,'TFile *f =','TFile *fs4 ='); p.patch_code(14,'f->Get','fs4->Get')
    p.code(14,'\n'.join(line for line in p.code(14).splitlines() if 'ProcessLine' not in line))
    p.md(16,'<p>寻峰给出候选位置，不会自动识别核素。本例中先按峰高取前六个候选，再按 channel 排序，选取与四个已知能量相符的峰组。这个选择只适用于当前示例谱。</p><h3>候选峰与已知能量的匹配</h3><p>推广到其他条时，可比较不同峰组的线性刻度残差，同时检查峰序、能量覆盖和预期谱线；最小残差本身不能排除误认峰。最终峰心由原始谱的局部拟合确定。</p>')
    p.patch_code(17,'sort(pe.begin(),pe.begin()+6);','if (pe.size() < 6) throw std::runtime_error("候选峰不足六个，请检查寻峰结果");\nsort(pe.begin(), pe.begin()+6);')
    p.patch_code(21,'p0 + p1 * mpe[i] - e[i]','e[i] - (p0 + p1 * mpe[i])')
    p.append(22,'<p>本例选取彼此分开的 α 峰，窄区间内先用 Gaussian 描述峰心。若局部本底或低能尾明显，应检查残差后调整模型和区间。下面的 <code>S</code> 返回拟合结果，<code>Q</code> 减少日志，<code>+</code> 保留前面各峰的曲线。</p>')
    c=p.code(24).replace('double ge[4];','double centroid[4], centroidError[4];').replace('ge[i] = par[i][0];','centroid[i] = par[i][0];\n    centroidError[i] = fg[i]->GetParError(1);')
    c=c.replace('par[i][0] =', 'if (int(fr) != 0 || !fr.Get() || !fr->IsValid()) throw std::runtime_error("峰拟合失败");\n    par[i][0] =',1)
    c=c.replace('fg[i]->SetParameters(cpe[i], mpe[i], 4);','fg[i]->SetParameters(cpe[i], mpe[i], 4);\n    fg[i]->SetParLimits(2, 0.2, 20);')
    p.code(24,c)
    p.code(25,'TGraphErrors *gr1 = new TGraphErrors(4, centroid, e, centroidError, nullptr);\ngr1->SetTitle("Energy calibration;Channel;Energy (MeV)");\ngr1->Draw("AP");\nTFitResultPtr calibrationFit = gr1->Fit("pol1", "S");\nTF1 *f2 = gr1->GetFunction("pol1");\nc1->Draw();')
    p.code(26,p.code(26).replace('f1->GetParameter(1)','f2->GetParameter(1)').replace('p0 + p1 * ge[i] - e[i]','e[i] - (p0 + p1 * centroid[i])').replace('4, ge,','4, centroid,'))
    p.code(27,p.code(27).replace('pe[0]*','pe[1]*').replace('//存在锯齿，需要在刻度前进行连续化。','// bin 宽度应与原始 ADC 步距和刻度斜率相称；不必随机改变道值。'))
    p.save()

def hit_arrays():
    p=Page(PAGES[10])
    # The runtime-sized notation is a leaflist, not a standard C++ declaration.
    p.append(0,'<p>上面的 <code>[xhit]</code>、<code>[yhit]</code> 表示事件中有效元素个数；实际 C++ 内存数组要给出容量上限。下文用固定容量 48、事件长度 phit/rhit 演示 ROOT 的 variable-length leaflist。</p>')
    p.replace('因为在绝大多数情况下，一个 DSSD 只有少数几条包含有用信息，数组中大部分元素都是无用的。','在本例中，一个事件通常只有少数条有信号。固定数组的零值可被 ROOT 压缩；hit 结构的主要优点是便于表达和处理有效条，而不是保证文件总会更小。')
    p.patch_code(19,'"abs(rid[0]-rid[1])','"rhit==2 && abs(rid[0]-rid[1])')
    p.patch_code(21,'"rhit ==2 &&','"phit==1 && rhit==2 &&')
    p.patch_code(23,'"rid[0] ==','"rhit==2 && rid[0] ==')
    p.patch_code(23,'"pid[0] ==','"phit==1 && rhit==2 && pid[0] ==')
    p.replace('对 pe 参数连续化，利用一般策略（选出拟合 $\\chi^2/\\text{NDF}$ 最小的一组作为实际的峰位-能量组合）完成 Pie 侧所有 48 条的能量刻度。','参照 3.1 节，完成 Pie 侧所有 48 条的能量刻度。用已知谱线、峰序和刻度残差检查候选峰匹配。')
    p.append(28,'<p>固定容量数组在每次 <code>Fill()</code> 前应满足 <code>0 ≤ phit,rhit ≤ 48</code>。示例文件的 <code>pee/ree</code> 单位为 keV，与 3.1 中的 MeV 相差 1000 倍。</p>')
    p.paragraph(28,'对 pe 参数连续化','<li>参照 3.1 节完成 Pie 侧所有 48 条的能量刻度。结合已知谱线、峰序和残差检查峰匹配，再比较各条的峰宽和拟合质量。</li>')
    p.save()

def interstrip():
    p=Page(PAGES[11])
    p.replace('E_{i+1} = k_i A_i + b_i.','E_{i+1} = k_{i+1} A_{i+1} + b_{i+1}.')
    p.replace('In routine ADC readout, positive pulses are usually recorded, so the most useful class of events is the two-strip positive-sharing event, for which the total deposited energy is approximately','本例电子学记录所选极性的脉冲幅度。对于两条都有有效信号、且电荷收集完整的 sharing 事件，刻度后的沉积能量近似满足')
    p.append(8,'<p>两个能量已知的条带给出两个斜率和截距。斜率在误差内一致时，可用共同斜率求增益比；这里只能求出截距之和，不能单独确定每条的截距。</p>')
    p.append(9,'<p><code>GetV1/GetV2</code> 按 Draw 表达式的顺序返回数值。先设置 <code>SetEstimate</code>，避免所选事例数超过内部缓冲区。TGraph 拷贝这些值；下一次 Draw 会刷新原缓冲区。</p>')
    p.code(11,'tree->SetEstimate(tree->GetEntries()+1);\n'+p.code(11))
    p.patch_code(15,'*re[14] - %f','*re[14] + %f')
    p.append(14,'<p>这里的直线拟合是初步刻度：两条的幅度都有涨落，普通 TGraph 的最小二乘只处理纵向残差。需要精确参数误差时，应使用含两轴误差的拟合，并传播斜率与截距的 covariance。</p>')
    p.append(16,'<p>能量重心是位置估计量，不等于已验证的亚条位置分辨率；还需用已知位置数据检查电荷比—位置关系。电荷损失和电子学串扰也不能只靠相邻双击来区分。</p>')
    p.save()

def correlation():
    p=Page(PAGES[12])
    p.replace('measuring large-angle multiple charged particles','measuring forward-angle multiple charged particles')
    p.md(3,'<h3>Multiplicity for X and Y Sides</h3><p>硬件 multiplicity 条件影响样本组成。软件阈值、读出效率和能量共享会使离线 hit 数与触发 hit 数不同；X 侧触发也不保证 Y 侧具有相同 multiplicity。</p>')
    p.md(5,'<p>多条信号可能来自多个粒子，也可能来自一个粒子的电荷共享或串扰。仅凭这张 multiplicity 图还不能确定各类的比例，下面继续检查条号和能量关联。</p>')
    p.replace('topologically guarantees no charge sharing','suppresses detectable neighboring-strip signals; sharing below threshold can remain')
    p.md(13,'<h3>1. 取出逐事例关联数据</h3><p>将所选事例直接交给 TGraph 做 unbinned 直线拟合，避免把 TH2 的 bin 中心当成测量值。TH2 用来显示同一批事例；并不是所有关联拟合都必须采用这种做法。</p>')
    p.code(14,'tree->SetEstimate(tree->GetEntries()+1);\ntree->Draw("d1x[12]:d1y[13]", c1213, "goff");\n'+p.code(14))
    p.replace('ROOT only supports robust fitting for polynomial functions.','此处的 ROB 由 ROOT linear fitter 执行，适用于参数线性的模型，并不限于多项式；一般非线性 TF1 不能直接套用这个选项。')
    p.code(16,p.code(16).replace('Standard Fit (Pulled by outliers)','Least squares').replace('Robust Fit (Resists outliers)','ROB'))
    p.md(17,'<h3>3. 残差与幅度的关系</h3><p>定义 residual 为 <code>d1x[12] − (p0 + p1*d1y[13])</code>。直线描述合适时，主条带应在零附近，且不随幅度出现系统趋势。若有趋势，应检查模型、两轴测量误差、阈值和残留混合事件；不能仅凭低能端事例较多就判定为“统计假象”，也不能据此排除电子学非线性。</p>')
    p.append(19,'<p>保存的是满足条件的 <em>x-y 候选组合</em>，一个原事件可能贡献多个组合；保留原事件编号便于追踪。局部 isolation cut 不能独立证明组合来自同一粒子。<code>IsInside(x,y)</code> 的坐标顺序要与画 cut 时的横、纵轴一致。</p>')
    p.patch_code(21,'4000,0,8000,4000,0,8000','1000,0,8000,1000,0,8000')
    p.save()

def normalization():
    p=Page(PAGES[13])
    c=p.code(2)
    c=re.sub(r'bool KeepPoint\(.*?\n}\n', '', c, flags=re.S)
    c=c.replace('parx[i][1] = 1.0','parx[i][1] = 0.0').replace('pary[i][1] = 1.0','pary[i][1] = 0.0')
    c=c.replace('inline double Ex', 'inline double Ex')
    c=c.replace('   // b_x, k_x','   // k=0 表示尚未刻度')
    c=c.replace('    }\n}\n\ninline double Ex','    }\n    parx[16][1] = 1.0; // 唯一参考尺度\n}\n\ninline double Ex')
    p.code(2,c)
    p.patch_code(6,'8000,0,8000,8000,0,8000','1000,0,8000,1000,0,8000')
    p.md(12,'<h3>拟合区间内的事例分布</h3><p>低幅度区的事例较多。若直线模型及误差假设成立，这本身不会使拟合有偏，也不是随机丢弃该区间事例的理由。下面保留全部通过物理选择的事例，用各条的 residual 检查整个幅度范围。</p>')
    c=p.code(15).replace('            if (!KeepPoint(target_raw)) continue;\n','')
    c=c.replace('        g[id]->Fit("pol1", "Q ROB");','        int status = g[id]->Fit("pol1", "Q ROB");\n        if (status != 0) throw std::runtime_error("strip fit failed");')
    c=c.replace('            double Eref = Ex(ix, xe);','            if (parx[ix][1] <= 0) continue;\n            double Eref = Ex(ix, xe);')
    c=c.replace('            double Eref = Ey(iy, ye);','            if (pary[iy][1] <= 0) continue;\n            double Eref = Ey(iy, ye);')
    c=c.replace('"chi2/ndf"','"RSS/NDF"')
    c=c.replace('        double b = f->GetParameter(0);','        double b = f->GetParameter(0);')
    # Anchor the chosen scale instead of refitting the reference into a new scale.
    c=c.replace('            parx[id][0] = b;\n            parx[id][1] = k;','            if (id == 16) { b = 0; k = 1; } // 固定参考条定义\n            parx[id][0] = b;\n            parx[id][1] = k;')
    p.code(15,c)
    p.append(14,'<p>本例 TGraph 没有逐点误差，输出的 residual sum of squares/NDF 带有幅度平方的量纲，不宜当作标准 χ²/NDF 或用其接近 1 来评价拟合。ROB 是对离群点较不敏感的回归，不会自动识别粒子或电荷共享。</p>')
    p.append(23,'<p>缺少可用事例的条保持 <code>k=0</code>，明确表示未刻度，不把默认恒等变换当作刻度结果。后续校验排除这些条，并报告数量；实际分析需另找刻度数据或将其标为无效通道。</p>')
    p.patch_code(27,'    Long64_t nentries =','    Long64_t skipped = 0;\n    Long64_t nentries =')
    p.patch_code(27,'        double cxe =','        if (px[ix][1]<=0 || py[iy][1]<=0) { ++skipped; continue; }\n        double cxe =')
    p.patch_code(27,'    c_check->Update();','    c_check->Update();\n    cout << "Input=" << nentries << ", calibrated=" << nentries-skipped\n         << ", unavailable calibration=" << skipped << endl;')
    p.md(29,'<h3>Discussion: Limitations and the Multi-path Approach</h3><p>逐组传播容易实现，但前面步骤的参数误差会传到后面，各条也会共享参考误差。传播步数少不等于误差可以忽略。还可从不同参考路径检查参数稳定性，见<a href="3.5_DSSD_FB_correlation_II_DSSD1_multi-path.html">Multi-path calibration 与误差传播</a>。该补充展示候选参数的组合；共享数据或参考条时，应同时考虑路径间的 covariance。</p>')
    p.append(30,'<p>这些数值仍在参考条的相对幅度尺度上，并非 MeV。事件循环中使用容量为 32 的数组，leaflist 再用 x1hit/y1hit 指定有效长度。保留事件编号以及未通过选择的原因，避免丢失各层之间的对应关系。</p>')
    p.save()

def multipath():
    p=Page(PAGES[14])
    p.patch_code(1,'4000,0,8000,4000,0,8000','1000,0,8000,1000,0,8000')
    p.append(0,r'''<h3>Covariance 与独立性</h3><p>上面的逐项平方和仅适用于忽略相关项的近似。令输入参数向量为 u，传播后的参数为 v(u)，一般公式为 \(C_v=J C_u J^T\)，其中 \(J_{ij}=\partial v_i/\partial u_j\)。同一次直线拟合的 slope 与 intercept 通常相关，不能遗漏它们的 covariance。</p><p>下面的小例子固定 X15 为相对单位的定义，三条路径使用互不重叠的 pixel 事例，并近似忽略探测器共同系统误差。代码保留每条路径内部 k、b 的 covariance。分别对 k、b 作 inverse-variance 平均只是便于演示的组合，不是一般情况下的最优联合估计。若循环使用同一 pixel 或共享一个有误差的参考，不能反复当作独立新信息迭代，否则会低估误差。</p>''')
    p.patch_code(4,'bool isCalibrated = false;','bool isCalibrated = false;\n    double ckb = 0; // Cov(k,b)')
    p.patch_code(4,'bool isValid = false;','bool isValid = false;\n    double cst = 0; // Cov(s,t)')
    p.patch_code(5,'+ X.vb;','+ X.vb + 2*p.t*X.ckb;\n    Y.ckb = p.s*p.t*X.vk + p.s*X.ckb + X.k*X.k*p.cst;')
    p.patch_code(6,'+ pow(Y.k*p.t/s2, 2) * p.vs;','+ pow(Y.k*p.t/s2, 2) * p.vs\n               - 2*p.t/p.s*Y.ckb - 2*Y.k*Y.k*p.t/(s2*p.s)*p.cst;\n    X.ckb = Y.ckb/p.s - p.t/s2*Y.vk\n          + Y.k*Y.k/(s2*p.s)*p.cst - Y.k*Y.k*p.t/s4*p.vs;')
    p.patch_code(7,'if (!c.isCalibrated) continue;','if (!c.isCalibrated || c.vk<=0 || c.vb<=0) continue;')
    p.patch_code(7,'    result.k  =','    if (swk<=0 || swb<=0) return result;\n    result.k  =')
    p.patch_code(7,'    result.isCalibrated = true;','    for (const auto& c : cands) {\n        if (c.isCalibrated && c.vk>0 && c.vb>0)\n            result.ckb += c.ckb / (c.vk*c.vb*swk*swb);\n    }\n    result.isCalibrated = true;')
    c=p.code(8).replace('    tree->Draw("xe:ye", cut, "goff");','    tree->SetEstimate(tree->GetEntries()+1);\n    tree->Draw("xe:ye", cut, "goff");')
    c=c.replace('    sort(absRes.begin(), absRes.end());\n    double sigma = 1.4826 * absRes[n / 2];','    vector<double> sortedRes = absRes; // 只排序副本，保留事例对应\n    sort(sortedRes.begin(), sortedRes.end());\n    double sigma = 1.4826 * sortedRes[n / 2];\n    if (sigma <= 0) return fit;')
    c=c.replace('    TFitResultPtr r =','    if (gClean.GetN() < 3) return fit;\n    TFitResultPtr r =')
    c=c.replace('        printf("  Pixel','        fit.cst = r->CovMatrix(1,0);\n        printf("  Pixel')
    p.code(8,c)
    p.patch_code(9,'    gROOT->GetListOfCanvases()->Clear();','    // 保留前面阶段的 canvas。')
    p.patch_code(9,'    c->Draw();','    c->Draw();\n    tree->ResetBranchAddresses(); // 局部变量即将离开作用域')
    p.patch_code(10,'1e-12, 1e-12, true','0.0, 0.0, true')
    p.append(2,'<p>先用 ROB 给初始直线，再用 residual 的稳健尺度选择主体条带。最终 LS 的误差是在这个选择和模型之下的条件误差；它未包含 cut 变化或误认组合带来的系统误差。</p>')
    p.save()

def multiplicity():
    p=Page(PAGES[15])
    p.replace('approximately 25, 25, and 30','approximately −25, −25, and −30')
    p.paragraph(10,'From the corrected correlation plots','<p>本参考文件的共同 offset 取 <code>b/k = −25, −25, −30</code>，分别对应 DSSD1、2、3。因此修正幅度是每条相对幅度加上 b/k，即分别减去 25、25、30。它们是当前参考刻度的经验常数；重新刻度后应从 multiplicity 关联重新确定。</p>')
    p.replace('subtracting the corresponding $b/k$ value','adding the corresponding $b/k$ value')
    p.replace('raw energy of the $i$-th hit','relatively normalized amplitude of the $i$-th hit')
    p.replace('from the raw energies','from the relatively normalized amplitudes')
    p.replace('0.006','0.0067')
    p.replace('which has negligible impact on the physics objectives of the study. Therefore, no further corrections are attempted in subsequent data processing.','即约 0.67%。本例先保留这项 residual；其能否忽略要与后续观测量要求比较，不能仅凭比例小就认定没有影响。')
    p.patch_code(5,'(4,1,5,4,1,5)','(9,-0.5,8.5,9,-0.5,8.5)')
    p.patch_code(9,'6,-3,3','7,-3.5,3.5')
    p.code(15,p.code(15).replace('gROOT->LoadMacro','gROOT->Macro'))
    p.patch_code(22,'c2->Divide(3,2);','c2->Divide(3,3);')
    p.replace('Determine the true number of incident particles','Determine the reconstructed particle multiplicity')
    p.append(27,'<p>能量相近或多个粒子共用同一条时，配对可能不唯一。保存未匹配和多解状态，不要强行给每个事件唯一“真值”。上面的变长数组写法表示 ROOT leaflist；程序内给数组设置容量。记录原事件编号，后续才能与其他探测器逐事件关联。</p>')
    p.save()

def telescope():
    p=Page(PAGES[16])
    p.replace('重建出的真实粒子数','在当前配对规则下重建出的粒子数')
    p.md(5,'<h3>一个重建粒子</h3><p>先选取相邻两层各有一个重建 hit 的事例，观察主条带和连续分布。连续分布可能含散射、反应、能量收集不完整及误配等成分，不能仅靠这张图确定来源。</p>')
    p.md(13,'<p>下面用两个方向的条号差都不超过 2（整数条件 <code>abs(Δstrip)&lt;3</code>）选择位置相容的候选。它能抑制一部分不相容事例，但不是“未发生反应”的充分判据；还应考虑几何对准、角度及分辨。</p><p><img src="fig/reaction_detector.png" alt="探测器中反应与位置关联示意"></p>')
    p.replace('选择未在探测器反应事件','选择位置相容的候选事件')
    p.code(15,p.code(15).replace('"hit2==1 && hit3==1 && abs(x1-x2)<3 && abs(y1-y2)<3"','"hit2==1 && hit3==1 && abs(x2-x3)<3 && abs(y2-y3)<3"'))
    for i in [10,12]: p.patch_code(i,'10,-5,5,10,-5,5','11,-5.5,5.5,11,-5.5,5.5')
    p.append(7,'<p>此处 Draw 对两个数组按同一下标组成点，并没有完成跨探测器的粒子配对。这些图用于观察未经重新配对的关联；后文再检查能量排序导致的误配。</p>')
    p.append(18,'<p>绝对刻度还依赖粒子种类、有效探测器厚度和能量损失模型。相对幅度图本身可以先用于关联检查，但不能直接把坐标标为 MeV。</p>')
    p.save()

if __name__=='__main__':
    import sys
    for name in sys.argv[1:] or ['calibration','hit_arrays','interstrip','correlation','normalization','multipath','multiplicity','telescope']:
        globals()[name]()
